version: '3'

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: library_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    networks:
      - network

  backend:
    image: backend:trabalho-final
    build:
      context: library_back
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: db
    volumes:
      - './library_back:/library_back'
    ports:
      - '8000:8000'
    depends_on:
      - db
    networks:
      - network

  library_front:
    image: library_front:trabalho-final
    build:
      context: library_front
      dockerfile: Dockerfile
    volumes:
      - './library_front:/library_front'
      - '/library_front/node_modules/'
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - network

  nginx:
    image: nginx:1.22.0-alpine
    container_name: library_nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - library_front
    depends_on:
      - library_front
    networks:
      - network

networks:
  network:
    driver: bridge